### ISSUE TITLE
Test Syntax Error in Swift 4

### ISSUE THREAD

**Issue by TheOtherDave** [VerbalExpressions/SwiftVerbalExpressions#12]
Somewhere along the line, `NSRegularExpressonOptions` became `NSRegularExpression.Options`, which is a struct instead of a class. This means that a few of `VerbalExpressions`s methods are mutating now that `.options` has value semantics instead of reference semantics. This, in turn, causes a syntax error in the `testSearchOneLine()` test (on line 197) because it declares `tester` as a let, but the `searchOneLine()` method is one of the newly-mutating methods.

I see three ways around this:
1) Make `tester` a var instead of a let, and just deal with having mutating functions.
2) Make `VerbalExpressions` a class instead of a struct.
3) Make `.options` a wrapper class for the "real" options.

(Personally, I'm torn between 2 & 3)

Anyway, I can submit a PR with everything updated to Swift 3/4 syntax (it compiles & tests under both language settings). Just let me know how you want this fixed.

**Comment by nubbel** [comment]
Thanks for bringing this to our attention!

I fixed this in master. 

Actually none of the workaround you proposed were necessary. The error was caused by bug in the [removeModifier](https://github.com/VerbalExpressions/SwiftVerbalExpressions/blob/8d79919cdee3c5afc81fbae0605b2f101f5f7cd8/VerbalExpressions/VerbalExpressions.swift#L222) function. 
By mistake, the mutation function `options.subtract()` was called instead of the non-mutating version `options.subtracting()`. The whole `VerbalExpressions` struct is immutable, functions only return new instances instead of mutating the struct value itself.
